# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
---
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]($REPO/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        - **({{ commit.scope }})** {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | split(pat="\n") | first }}
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
            - {% if commit.breaking %}[**breaking**] {% endif %}\
                {{ commit.message | split(pat="\n") | first }}
            {%- if commit.body %}
            {%- for line in commit.body | split(pat="\n") %}
                  {{ line }}
            {%- endfor %}
            {%- endif %}
        {% endif -%}
    {% endfor -%}
{% endfor %}\n
"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
require_conventional = false
split_commits = false
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat", group = "🚀 Features" },
    { message = "^fix", group = "🐛 Bug Fixes" },
    { message = "^doc", group = "📚 Documentation" },
    { message = "^perf", group = "⚡ Performance" },
    { message = "^refactor", group = "🚜 Refactor" },
    { message = "^style", group = "🎨 Styling" },
    { message = "^test", group = "🧪 Testing" },
    { message = "^build", group = "🔧 Build" },
    { message = "^ci", group = "🔧 CI/CD" },
    { message = "^chore", group = "⚙️ Maintenance" },
    { body = ".*security", group = "🛡️ Security" },
    { message = "^revert", group = "🔙 Reverts" },
    { message = ".*", group = "📦 Other Changes" },
]
filter_commits = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"

[git.link]
github = { owner = "timjonaswechler", repo = "fos_client" }
