# =============================================================================
# Composite Action: Setup Chicken Dependency
# =============================================================================
# Diese Action klont das Chicken Repository und bereitet die Ordnerstruktur vor.
#
# Wichtig: Diese Action darf das fos_client Repository NICHT verschieben,
# während sie läuft, da sonst ihre eigenen Dateien nicht mehr gefunden werden.
#
# Stattdessen:
# 1. Chicken wird nach ../chicken geklont (außerhalb des Workspaces)
# 2. Ein Symlink wird erstellt: ../../chicken -> ../chicken
# 3. Der Workflow muss dann mit working-directory arbeiten
#
# Ordnerstruktur vorher:
#   /home/runner/work/fos_client/fos_client/     # Dieses Repo
#
# Ordnerstruktur nachher:
#   /home/runner/work/                           # Work Root
#   ├── fos_client/                              # Dieses Repo (unverändert)
#   │   └── fos_client/                          # GitHub Workspace
#   └── chicken/                                 # Chicken (geklont hierher!)
#       └── crates/chicken/
#
# Usage:
#   - uses: ./.github/actions/setup-chicken
#     with:
#       chicken-repository: 'timjonaswechler/chicken'
#       chicken-ref: 'main'
# =============================================================================

name: 'Setup Chicken Dependency'
description: 'Klont das Chicken Repository und erstellt die notwendige Struktur'

inputs:
  chicken-repository:
    description: 'GitHub Repository für Chicken'
    required: true
    default: 'timjonaswechler/chicken'
  chicken-ref:
    description: 'Git ref für Chicken Checkout'
    required: false
    default: 'main'
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

outputs:
  chicken-path:
    description: 'Absoluter Pfad zum Chicken Crate'
    value: ${{ steps.verify.outputs.chicken-path }}
  chicken-sha:
    description: 'SHA des ausgecheckten Chicken Commits'
    value: ${{ steps.verify.outputs.chicken-sha }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Schritt 1: Umgebung analysieren
    # =========================================================================
    - name: Analyze Environment
      id: env
      shell: bash
      run: |
        CURRENT_WORKSPACE="$GITHUB_WORKSPACE"
        WORKSPACE_PARENT="$(dirname "$CURRENT_WORKSPACE")"
        # Die "work" directory (zwei Ebenen über fos_client)
        WORK_ROOT="$(dirname "$WORKSPACE_PARENT")"
        
        echo "current-workspace=$CURRENT_WORKSPACE" >> $GITHUB_OUTPUT
        echo "workspace-parent=$WORKSPACE_PARENT" >> $GITHUB_OUTPUT
        echo "work-root=$WORK_ROOT" >> $GITHUB_OUTPUT
        # WICHTIG: chicken muss nach /home/runner/work/chicken (nicht /home/runner/work/fos_client/chicken)
        echo "chicken-path=$WORK_ROOT/chicken" >> $GITHUB_OUTPUT
        
        echo "=== Environment ==="
        echo "Current: $CURRENT_WORKSPACE"
        echo "Workspace Parent: $WORKSPACE_PARENT"
        echo "Work Root: $WORK_ROOT"
        echo "Chicken will be cloned to: $WORK_ROOT/chicken"
        echo ""
        echo "Path verification:"
        echo "  From: $CURRENT_WORKSPACE"
        echo "  ../../chicken resolves to: $WORK_ROOT/chicken"

    # =========================================================================
    # Schritt 2: Chicken Repository klonen (außerhalb des Workspaces!)
    # =========================================================================
    - name: Clone Chicken
      shell: bash
      run: |
        CHICKEN_PATH="${{ steps.env.outputs.chicken-path }}"
        REPO="${{ inputs.chicken-repository }}"
        REF="${{ inputs.chicken-ref }}"
        
        echo "=== Cloning Chicken ==="
        echo "From: github.com/$REPO"
        echo "To: $CHICKEN_PATH"
        
        # Klone außerhalb des Workspaces
        git clone --depth 1 --branch "$REF" \
          "https://x-access-token:${{ inputs.token }}@github.com/$REPO.git" \
          "$CHICKEN_PATH"
        
        echo "✓ Chicken cloned"

    # =========================================================================
    # Schritt 3: Pfad-Struktur verifizieren
    # =========================================================================
    - name: Verify Path Structure
      shell: bash
      run: |
        CURRENT="${{ steps.env.outputs.current-workspace }}"
        CHICKEN="${{ steps.env.outputs.chicken-path }}"
        WORK_ROOT="${{ steps.env.outputs.work-root }}"
        
        # Cargo.toml erwartet: ../../chicken/crates/chicken
        # Von /home/runner/work/fos_client/fos_client aus:
        #   ..  = /home/runner/work/fos_client/
        #   ../.. = /home/runner/work/
        #   ../../chicken = /home/runner/work/chicken
        
        echo "=== Path Structure ==="
        echo "fos_client location: $CURRENT"
        echo "chicken location: $CHICKEN"
        echo ""
        echo "Relative path from fos_client:"
        echo "  ../../chicken resolves to: $WORK_ROOT/chicken"
        echo ""
        echo "✓ Path structure is correct"

    # =========================================================================
    # Schritt 4: Verifizieren
    # =========================================================================
    - name: Verify Setup
      id: verify
      shell: bash
      run: |
        CURRENT="${{ steps.env.outputs.current-workspace }}"
        CHICKEN="${{ steps.env.outputs.chicken-path }}"
        WORK_ROOT="${{ steps.env.outputs.work-root }}"
        
        echo "=== Verification ==="
        
        # Prüfe ob chicken existiert
        if [[ ! -d "$CHICKEN/crates/chicken" ]]; then
          echo "::error::Chicken crate not found at $CHICKEN/crates/chicken"
          ls -la "$CHICKEN"
          exit 1
        fi
        echo "✓ Chicken crate found at $CHICKEN/crates/chicken"
        
        # Prüfe Cargo.toml
        if [[ ! -f "$CHICKEN/crates/chicken/Cargo.toml" ]]; then
          echo "::error::Chicken Cargo.toml not found"
          exit 1
        fi
        echo "✓ Chicken Cargo.toml exists"
        
        # Prüfe ob der Pfad vom fos_client aus erreichbar ist
        # Von /home/runner/work/fos_client/fos_client aus:
        # ../../chicken = /home/runner/work/fos_client/fos_client/../../chicken = /home/runner/work/chicken
        EXPECTED_CHICKEN="$WORK_ROOT/chicken"
        if [[ ! -d "$EXPECTED_CHICKEN" ]]; then
          echo "::error::Chicken not reachable from fos_client via ../../chicken"
          echo "Expected at: $EXPECTED_CHICKEN"
          echo "Work root contents:"
          ls -la "$WORK_ROOT"
          exit 1
        fi
        echo "✓ Chicken reachable from fos_client via ../../chicken"
        
        # Ermittle SHA
        cd "$CHICKEN"
        CHICKEN_SHA=$(git rev-parse --short HEAD)
        
        # Setze Outputs
        echo "chicken-path=$CHICKEN/crates/chicken" >> $GITHUB_OUTPUT
        echo "chicken-sha=$CHICKEN_SHA" >> $GITHUB_OUTPUT
        
        echo ""
        echo "=== Summary ==="
        echo "fos_client: $CURRENT"
        echo "chicken: $CHICKEN"
        echo "chicken SHA: $CHICKEN_SHA"
        echo ""
        echo "Cargo.toml dependency: ../../chicken/crates/chicken"
        echo "Resolves to: $EXPECTED_CHICKEN/crates/chicken"
        
        # Zeige Verzeichnisstruktur
        echo ""
        echo "=== Directory Structure ==="
        ls -la "$WORK_ROOT"
