# =============================================================================
# Composite Action: Setup Chicken Dependency
# =============================================================================
# Diese Action klont das Chicken Repository und bereitet die Ordnerstruktur vor.
#
# Wichtig: Diese Action darf das fos_client Repository NICHT verschieben,
# während sie läuft, da sonst ihre eigenen Dateien nicht mehr gefunden werden.
#
# Stattdessen:
# 1. Chicken wird nach ../chicken geklont (außerhalb des Workspaces)
# 2. Ein Symlink wird erstellt: ../../chicken -> ../chicken
# 3. Der Workflow muss dann mit working-directory arbeiten
#
# Ordnerstruktur vorher:
#   /home/runner/work/fos_client/fos_client/     # Dieses Repo
#
# Ordnerstruktur nachher:
#   /home/runner/work/fos_client/
#   ├── fos_client/                              # Dieses Repo (unverändert)
#   ├── chicken/                                 # Chicken (geklont)
#   └── chicken_link/ -> chicken/               # Symlink für Cargo
#
# Usage:
#   - uses: ./.github/actions/setup-chicken
#     with:
#       chicken-repository: 'timjonaswechler/chicken'
#       chicken-ref: 'main'
# =============================================================================

name: 'Setup Chicken Dependency'
description: 'Klont das Chicken Repository und erstellt die notwendige Struktur'

inputs:
  chicken-repository:
    description: 'GitHub Repository für Chicken'
    required: true
    default: 'timjonaswechler/chicken'
  chicken-ref:
    description: 'Git ref für Chicken Checkout'
    required: false
    default: 'main'
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

outputs:
  chicken-path:
    description: 'Absoluter Pfad zum Chicken Crate'
    value: ${{ steps.verify.outputs.chicken-path }}
  chicken-sha:
    description: 'SHA des ausgecheckten Chicken Commits'
    value: ${{ steps.verify.outputs.chicken-sha }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Schritt 1: Umgebung analysieren
    # =========================================================================
    - name: Analyze Environment
      id: env
      shell: bash
      run: |
        CURRENT_WORKSPACE="$GITHUB_WORKSPACE"
        WORKSPACE_PARENT="$(dirname "$CURRENT_WORKSPACE")"
        
        echo "current-workspace=$CURRENT_WORKSPACE" >> $GITHUB_OUTPUT
        echo "workspace-parent=$WORKSPACE_PARENT" >> $GITHUB_OUTPUT
        echo "chicken-path=$WORKSPACE_PARENT/chicken" >> $GITHUB_OUTPUT
        
        echo "=== Environment ==="
        echo "Current: $CURRENT_WORKSPACE"
        echo "Parent: $WORKSPACE_PARENT"
        echo "Chicken will be cloned to: $WORKSPACE_PARENT/chicken"

    # =========================================================================
    # Schritt 2: Chicken Repository klonen (außerhalb des Workspaces!)
    # =========================================================================
    - name: Clone Chicken
      shell: bash
      run: |
        CHICKEN_PATH="${{ steps.env.outputs.chicken-path }}"
        REPO="${{ inputs.chicken-repository }}"
        REF="${{ inputs.chicken-ref }}"
        
        echo "=== Cloning Chicken ==="
        echo "From: github.com/$REPO"
        echo "To: $CHICKEN_PATH"
        
        # Klone außerhalb des Workspaces
        git clone --depth 1 --branch "$REF" \
          "https://x-access-token:${{ inputs.token }}@github.com/$REPO.git" \
          "$CHICKEN_PATH"
        
        echo "✓ Chicken cloned"

    # =========================================================================
    # Schritt 3: Symlink für Cargo Path-Dependency erstellen
    # =========================================================================
    - name: Create Symlink for Cargo
      shell: bash
      run: |
        CURRENT="${{ steps.env.outputs.current-workspace }}"
        WORKSPACE_PARENT="${{ steps.env.outputs.workspace-parent }}"
        
        # Cargo erwartet: ../../chicken/crates/chicken
        # Das ist relativ zu: /home/runner/work/fos_client/fos_client
        # Also: /home/runner/work/chicken
        
        # Erstelle Symlink: ../../chicken -> ../chicken
        # Aber wir müssen vom fos_client Verzeichnis ausgehen
        
        # Eigentlich brauchen wir:
        # /home/runner/work/fos_client/fos_client/../../chicken
        # = /home/runner/work/chicken
        
        # Da wir nichts verschieben, passt der Pfad bereits!
        # ../../chicken von /home/runner/work/fos_client/fos_client aus
        # zeigt auf /home/runner/work/chicken
        
        echo "✓ Path structure ready"
        echo "  From: $CURRENT"
        echo "  Chicken: $WORKSPACE_PARENT/chicken"
        echo "  Relative path: ../../chicken"

    # =========================================================================
    # Schritt 4: Verifizieren
    # =========================================================================
    - name: Verify Setup
      id: verify
      shell: bash
      run: |
        CURRENT="${{ steps.env.outputs.current-workspace }}"
        CHICKEN="${{ steps.env.outputs.chicken-path }}"
        
        echo "=== Verification ==="
        
        # Prüfe ob chicken existiert
        if [[ ! -d "$CHICKEN/crates/chicken" ]]; then
          echo "::error::Chicken crate not found at $CHICKEN/crates/chicken"
          ls -la "$CHICKEN"
          exit 1
        fi
        echo "✓ Chicken crate found"
        
        # Prüfe Cargo.toml
        if [[ ! -f "$CHICKEN/crates/chicken/Cargo.toml" ]]; then
          echo "::error::Chicken Cargo.toml not found"
          exit 1
        fi
        echo "✓ Chicken Cargo.toml exists"
        
        # Prüfe ob der Pfad vom fos_client aus erreichbar ist
        EXPECTED_CHICKEN="$CURRENT/../../chicken"
        if [[ ! -d "$EXPECTED_CHICKEN" ]]; then
          echo "::error::Chicken not reachable from fos_client via ../../chicken"
          echo "Expected at: $EXPECTED_CHICKEN"
          ls -la "$CURRENT/../"
          exit 1
        fi
        echo "✓ Chicken reachable from fos_client"
        
        # Ermittle SHA
        cd "$CHICKEN"
        CHICKEN_SHA=$(git rev-parse --short HEAD)
        
        # Setze Outputs
        echo "chicken-path=$CHICKEN/crates/chicken" >> $GITHUB_OUTPUT
        echo "chicken-sha=$CHICKEN_SHA" >> $GITHUB_OUTPUT
        
        echo ""
        echo "=== Summary ==="
        echo "fos_client: $CURRENT"
        echo "chicken: $CHICKEN"
        echo "chicken SHA: $CHICKEN_SHA"
        echo ""
        echo "Cargo.toml dependency path: ../../chicken/crates/chicken"
        
        # Zeige beide Verzeichnisse
        echo ""
        echo "=== Directory Structure ==="
        ls -la "$(dirname "$CURRENT")"
