# =============================================================================
# Composite Action: Setup Chicken Dependency
# =============================================================================
# Diese Action klont das Chicken Repository in die korrekte Ordnerstruktur.
#
# Ordnerstruktur nach Setup:
#   /home/runner/work/fos_client/     # GitHub Workspace (fos_client ist hier)
#   ├── fos_client/                   # Wird nach ../fos/fos_client verschoben
#   └── chicken/                      # Wird nach ../chicken geklont
#
# Am Ende:
#   /home/runner/work/
#   ├── fos/fos_client/               # Dieses Repo
#   └── chicken/crates/chicken/       # Chicken Dependency
#
# Usage:
#   - uses: ./.github/actions/setup-chicken
#     with:
#       chicken-repository: 'your-org/chicken'
#       chicken-ref: 'main'
# =============================================================================

name: 'Setup Chicken Dependency'
description: 'Klont das Chicken Repository in die korrekte Ordnerstruktur'

inputs:
  chicken-repository:
    description: 'GitHub Repository für Chicken (Format: owner/repo)'
    required: true
    default: 'tim-jonaswechler/chicken'
  chicken-ref:
    description: 'Git ref für Chicken Checkout'
    required: false
    default: 'main'
  token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}

outputs:
  fos-client-path:
    description: 'Pfad zu fos_client'
    value: ${{ steps.setup.outputs.fos-client-path }}
  chicken-path:
    description: 'Pfad zu chicken crate'
    value: ${{ steps.setup.outputs.chicken-path }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Schritt 1: Pfade analysieren
    # =========================================================================
    - name: Analyze Paths
      id: paths
      shell: bash
      run: |
        # GitHub Actions checkt aus nach: /home/runner/work/fos_client/fos_client
        # Wir müssen umstrukturieren auf:
        #   /home/runner/work/fos/fos_client
        #   /home/runner/work/chicken
        
        CURRENT_WORKSPACE="$GITHUB_WORKSPACE"
        WORKSPACE_ROOT="$(dirname "$CURRENT_WORKSPACE")"
        
        echo "current-workspace=$CURRENT_WORKSPACE" >> $GITHUB_OUTPUT
        echo "workspace-root=$WORKSPACE_ROOT" >> $GITHUB_OUTPUT
        echo "fos-target=$WORKSPACE_ROOT/fos/fos_client" >> $GITHUB_OUTPUT
        echo "chicken-target=$WORKSPACE_ROOT/chicken" >> $GITHUB_OUTPUT
        
        echo "=== Environment Analysis ==="
        echo "Current Workspace: $CURRENT_WORKSPACE"
        echo "Workspace Root: $WORKSPACE_ROOT"
        echo "FOS Target: $WORKSPACE_ROOT/fos/fos_client"
        echo "Chicken Target: $WORKSPACE_ROOT/chicken"

    # =========================================================================
    # Schritt 2: Verzeichnisstruktur vorbereiten
    # =========================================================================
    - name: Prepare Directory Structure
      shell: bash
      run: |
        WORKSPACE_ROOT="${{ steps.paths.outputs.workspace-root }}"
        
        # Erstelle Zielverzeichnisse
        mkdir -p "$WORKSPACE_ROOT/fos"
        mkdir -p "$WORKSPACE_ROOT/chicken"
        
        echo "✓ Directory structure prepared"

    # =========================================================================
    # Schritt 3: Chicken mit git clone (nicht actions/checkout)
    # =========================================================================
    - name: Clone Chicken Repository
      shell: bash
      run: |
        CHICKEN_TARGET="${{ steps.paths.outputs.chicken-target }}"
        REPO="${{ inputs.chicken-repository }}"
        REF="${{ inputs.chicken-ref }}"
        
        echo "=== Cloning Chicken ==="
        echo "Repository: $REPO"
        echo "Ref: $REF"
        echo "Target: $CHICKEN_TARGET"
        
        # Clone mit Token für private Repos
        git clone --depth 1 --branch "$REF" \
          "https://x-access-token:${{ inputs.token }}@github.com/$REPO.git" \
          "$CHICKEN_TARGET"
        
        echo "✓ Chicken cloned successfully"
        
        # Zeige was wir haben
        ls -la "$CHICKEN_TARGET"

    # =========================================================================
    # Schritt 4: fos_client verschieben
    # =========================================================================
    - name: Move fos_client
      shell: bash
      run: |
        CURRENT="${{ steps.paths.outputs.current-workspace }}"
        TARGET="${{ steps.paths.outputs.fos-target }}"
        
        echo "=== Moving fos_client ==="
        echo "From: $CURRENT"
        echo "To: $TARGET"
        
        # Verschiebe das Repository
        mv "$CURRENT" "$TARGET"
        
        echo "✓ fos_client moved successfully"

    # =========================================================================
    # Schritt 5: Struktur verifizieren
    # =========================================================================
    - name: Verify and Output
      id: setup
      shell: bash
      run: |
        WORKSPACE_ROOT="${{ steps.paths.outputs.workspace-root }}"
        FOS_PATH="$WORKSPACE_ROOT/fos/fos_client"
        CHICKEN_PATH="$WORKSPACE_ROOT/chicken"
        
        echo "=== Verifying Structure ==="
        
        # Prüfe fos_client
        if [[ ! -d "$FOS_PATH" ]]; then
          echo "::error::fos_client not found at $FOS_PATH"
          exit 1
        fi
        echo "✓ fos_client: $FOS_PATH"
        
        # Prüfe Cargo.toml
        if [[ ! -f "$FOS_PATH/Cargo.toml" ]]; then
          echo "::error::Cargo.toml not found"
          exit 1
        fi
        echo "✓ Cargo.toml exists"
        
        # Prüfe chicken
        if [[ ! -d "$CHICKEN_PATH/crates/chicken" ]]; then
          echo "::error::Chicken crate not found at $CHICKEN_PATH/crates/chicken"
          echo "Contents of $CHICKEN_PATH:"
          ls -la "$CHICKEN_PATH"
          exit 1
        fi
        echo "✓ chicken: $CHICKEN_PATH/crates/chicken"
        
        # Prüfe chicken Cargo.toml
        if [[ ! -f "$CHICKEN_PATH/crates/chicken/Cargo.toml" ]]; then
          echo "::error::Chicken Cargo.toml not found"
          exit 1
        fi
        echo "✓ Chicken Cargo.toml exists"
        
        # Ermittle SHA
        cd "$CHICKEN_PATH"
        CHICKEN_SHA=$(git rev-parse --short HEAD)
        
        # Setze Outputs
        echo "fos-client-path=$FOS_PATH" >> $GITHUB_OUTPUT
        echo "chicken-path=$CHICKEN_PATH/crates/chicken" >> $GITHUB_OUTPUT
        
        # Update GITHUB_WORKSPACE für nachfolgende Steps
        echo "GITHUB_WORKSPACE=$FOS_PATH" >> $GITHUB_ENV
        
        echo ""
        echo "=== Final Structure ==="
        echo "FOS_CLIENT: $FOS_PATH"
        echo "CHICKEN: $CHICKEN_PATH (SHA: $CHICKEN_SHA)"
        
        # Zeige Struktur
        echo ""
        echo "=== Directory Tree ==="
        tree -L 3 "$WORKSPACE_ROOT" 2>/dev/null || find "$WORKSPACE_ROOT" -maxdepth 3 -type d | sort
        
        # Prüfe Cargo.toml
        echo ""
        echo "=== Cargo.toml chicken dependency ==="
        grep -A2 "chicken" "$FOS_PATH/Cargo.toml" || echo "No chicken dependency found"
