# =============================================================================
# Composite Action: Setup Chicken Dependency
# =============================================================================
# Diese Action klont das Chicken Repository in die korrekte Ordnerstruktur,
# die für den lokalen Path-Dependency in Cargo.toml benötigt wird.
#
# Ordnerstruktur nach Setup:
#   /home/runner/work/
#   ├── fos/fos_client/          # Dieses Repo (wird hierhin verschoben)
#   └── chicken/crates/chicken/  # Chicken Dependency (wird hierhin geklont)
#
# Usage:
#   - uses: ./.github/actions/setup-chicken
#     with:
#       chicken-repository: 'your-org/chicken'
#       chicken-ref: 'main'
# =============================================================================

name: 'Setup Chicken Dependency'
description: 'Klont das Chicken Repository in die korrekte Ordnerstruktur für Cargo Path-Dependencies'

inputs:
  chicken-repository:
    description: 'GitHub Repository für Chicken (Format: owner/repo)'
    required: true
    default: 'tim-jonaswechler/chicken'
  chicken-ref:
    description: 'Git ref für Chicken Checkout (branch, tag, sha)'
    required: false
    default: 'main'
  token:
    description: 'GitHub Token für private Repositories'
    required: false
    default: ${{ github.token }}

outputs:
  chicken-path:
    description: 'Absoluter Pfad zum Chicken Crate'
    value: ${{ steps.verify.outputs.chicken-path }}
  chicken-sha:
    description: 'SHA des ausgecheckten Chicken Commits'
    value: ${{ steps.verify.outputs.chicken-sha }}
  fos-client-path:
    description: 'Absoluter Pfad zum fos_client'
    value: ${{ steps.verify.outputs.fos-client-path }}

runs:
  using: 'composite'
  steps:
    # =========================================================================
    # Schritt 1: Pfade berechnen und Umgebung verstehen
    # =========================================================================
    - name: Calculate Paths
      id: paths
      shell: bash
      run: |
        # GitHub Actions checkt standardmäßig aus nach:
        # /home/runner/work/fos_client/fos_client
        # 
        # Wir brauchen:
        # /home/runner/work/fos/fos_client
        # /home/runner/work/chicken/crates/chicken
        
        ORIGINAL_WORKSPACE="$GITHUB_WORKSPACE"
        WORKSPACE_PARENT="$(dirname "$ORIGINAL_WORKSPACE")"
        
        echo "original-workspace=$ORIGINAL_WORKSPACE" >> $GITHUB_OUTPUT
        echo "workspace-parent=$WORKSPACE_PARENT" >> $GITHUB_OUTPUT
        echo "fos-path=$WORKSPACE_PARENT/fos/fos_client" >> $GITHUB_OUTPUT
        echo "chicken-path=$WORKSPACE_PARENT/chicken" >> $GITHUB_OUTPUT
        
        echo "=== Initial Environment ==="
        echo "Original GITHUB_WORKSPACE: $ORIGINAL_WORKSPACE"
        echo "Workspace Parent: $WORKSPACE_PARENT"
        echo "Current Directory: $(pwd)"
        ls -la "$WORKSPACE_PARENT" || echo "Parent directory listing failed"

    # =========================================================================
    # Schritt 2: Chicken Repository clonen (VOR dem Verschieben!)
    # =========================================================================
    - name: Checkout Chicken Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.chicken-repository }}
        ref: ${{ inputs.chicken-ref }}
        path: ${{ steps.paths.outputs.workspace-parent }}/chicken
        token: ${{ inputs.token }}
        fetch-depth: 1

    # =========================================================================
    # Schritt 3: fos_client in die korrekte Struktur verschieben
    # =========================================================================
    - name: Move fos_client to Correct Location
      shell: bash
      run: |
        WORKSPACE_PARENT="${{ steps.paths.outputs.workspace-parent }}"
        ORIGINAL="${{ steps.paths.outputs.original-workspace }}"
        TARGET="$WORKSPACE_PARENT/fos/fos_client"
        
        echo "=== Moving fos_client ==="
        echo "From: $ORIGINAL"
        echo "To: $TARGET"
        
        # Erstelle Zielverzeichnis
        mkdir -p "$WORKSPACE_PARENT/fos"
        
        # Verschiebe das Repository
        if [[ -d "$ORIGINAL" ]]; then
          mv "$ORIGINAL" "$TARGET"
          echo "✓ fos_client moved successfully"
        else
          echo "::error::Original directory not found: $ORIGINAL"
          exit 1
        fi
        
        # Setze neue Umgebungsvariablen
        echo "GITHUB_WORKSPACE=$TARGET" >> $GITHUB_ENV
        echo "FOS_CLIENT_PATH=$TARGET" >> $GITHUB_ENV
        echo "CHICKEN_PATH=$WORKSPACE_PARENT/chicken" >> $GITHUB_ENV

    # =========================================================================
    # Schritt 4: Struktur verifizieren
    # =========================================================================
    - name: Verify Structure
      id: verify
      shell: bash
      run: |
        WORKSPACE_PARENT="${{ steps.paths.outputs.workspace-parent }}"
        FOS_PATH="$WORKSPACE_PARENT/fos/fos_client"
        CHICKEN_PATH="$WORKSPACE_PARENT/chicken"
        
        echo "=== Verifying Directory Structure ==="
        
        # Prüfe fos_client
        if [[ ! -d "$FOS_PATH" ]]; then
          echo "::error::fos_client not found at: $FOS_PATH"
          exit 1
        fi
        echo "✓ fos_client found at: $FOS_PATH"
        
        # Prüfe Cargo.toml
        if [[ ! -f "$FOS_PATH/Cargo.toml" ]]; then
          echo "::error::Cargo.toml not found in fos_client"
          ls -la "$FOS_PATH"
          exit 1
        fi
        echo "✓ Cargo.toml found"
        
        # Prüfe chicken
        if [[ ! -d "$CHICKEN_PATH/crates/chicken" ]]; then
          echo "::error::Chicken crate not found at: $CHICKEN_PATH/crates/chicken"
          echo "Contents of $CHICKEN_PATH:"
          ls -la "$CHICKEN_PATH" || echo "Cannot list chicken directory"
          exit 1
        fi
        echo "✓ Chicken found at: $CHICKEN_PATH/crates/chicken"
        
        # Prüfe chicken Cargo.toml
        if [[ ! -f "$CHICKEN_PATH/crates/chicken/Cargo.toml" ]]; then
          echo "::error::Cargo.toml not found in chicken crate"
          exit 1
        fi
        echo "✓ Chicken Cargo.toml found"
        
        # Ermittle Chicken SHA
        cd "$CHICKEN_PATH"
        CHICKEN_SHA=$(git rev-parse --short HEAD)
        
        # Setze Outputs
        echo "chicken-path=$CHICKEN_PATH/crates/chicken" >> $GITHUB_OUTPUT
        echo "chicken-sha=$CHICKEN_SHA" >> $GITHUB_OUTPUT
        echo "fos-client-path=$FOS_PATH" >> $GITHUB_OUTPUT
        
        echo ""
        echo "=== Final Structure ==="
        echo "fos_client: $FOS_PATH"
        echo "chicken: $CHICKEN_PATH (SHA: $CHICKEN_SHA)"
        
        # Zeige die Struktur
        echo ""
        echo "=== Directory Tree ==="
        tree -L 3 "$WORKSPACE_PARENT" 2>/dev/null || find "$WORKSPACE_PARENT" -maxdepth 3 -type d | sort | head -20
        
        echo ""
        echo "=== Cargo.toml Dependency Check ==="
        grep -A2 "chicken" "$FOS_PATH/Cargo.toml" || echo "No chicken dependency found in Cargo.toml"

    # =========================================================================
    # Schritt 5: Working Directory setzen
    # =========================================================================
    - name: Set Working Directory
      shell: bash
      run: |
        FOS_PATH="${{ steps.verify.outputs.fos-client-path }}"
        echo "Setting working directory to: $FOS_PATH"
        cd "$FOS_PATH"
        pwd
        ls -la
